version: "3"
services:
  postgres_db:
    image: postgres:12
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=doctorCRM
    ports:
      - "5000:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data