version: "3"
services:
  postgres_db:
    image: postgres:12
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=doctorCRM
    ports:
      - "5000:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  #
  redis:
    image: redis:6.0.4
    container_name: redis
    ports:
      - "6379:6379"

  # Not used during development
  nginx:
    image: nginx:1.17
    container_name: nginx
    network_mode: host
    volumes:
    - ./src/app/static:/app/static/
    - ./src/nginx.conf:/etc/nginx/nginx.conf
    - ./venv/lib/python3.5/site-packages/django/contrib/admin/static/admin/:/app/static/admin/
